[package]
name = "circuit"
type = "bin"
authors = [""]

[dependencies]
ec = { git = "https://github.com/noir-lang/noir-edwards", tag = "v0.2.1"}
binary_merkle_root = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "binary-merkle-root-v0.0.1", directory = "packages/binary-merkle-root" }
poseidon = { tag = "v0.1.0", git = "https://github.com/noir-lang/poseidon" }